### ISSUE TITLE
Not supported in Linux Alpine

### ISSUE THREAD

**Issue by robgero** [janlelis/fancy_irb#12]
When used in Linux alpine, `RbConfig::CONFIG['host_os']` is equal to `"linux-musl"`

When the constant `TPUT` is getting set the `RbConfig::CONFIG['host_os'] =~ /linux/ ` condition passes, attempting to run the `script` command, which is not installed on alpine by default.

https://github.com/janlelis/fancy_irb/blob/58958f5503b87ee738107c93977cce70a036aff3/lib/fancy_irb/terminal_info.rb#L17-L47

This leaves us with an ugly error and a non-colored console, however the console still works fine.

```
docker-container:~/app$ bundle exec rails c
sh: script: not found
sh: script: not found
sh: script: not found
sh: script: not found
application(production)>
```

To install script on alpine, you must install the `util-linux` package, which is very large, and we are trying to keep our docker containers sizes to a minimum.

If the following block of code is run instead when `RbConfig::CONFIG['host_os'] == "linux-musl"`, it will fix this issue.

https://github.com/janlelis/fancy_irb/blob/58958f5503b87ee738107c93977cce70a036aff3/lib/fancy_irb/terminal_info.rb#L33-L38

**Comment by janlelis** [comment]
Thanks a lot for this detailed bug report! Fixed in v1.4.2.
